### ISSUE TITLE
add pagination to pages in a section

### ISSUE THREAD

**Issue by roxiomontes** [anitab-org/open-source-day#3]
would like to have "previous" and "next" buttons on the https://anitab-org.github.io/open-source-day/open-source-day-2021-summer/ section

example:
https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/
![image](https://user-images.githubusercontent.com/14279937/119307635-d432b380-bc20-11eb-9c97-76ae08968a05.png)

Resources:
https://mmistakes.github.io/minimal-mistakes/docs/configuration/#plugins
https://mmistakes.github.io/minimal-mistakes/docs/configuration/#paginate

**Comment by rachejazz** [comment]
@roxiomontes the github.io page gives a 404. Can you update it?

**Comment by aakash-kumar-gorai** [comment]
please update the link https://anitab-org.github.io/open-source-day/open-source-day-2021-summer/
